name: Build Docker image

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

permissions:
  contents: read

env:
  IMAGE_FILE: /tmp/zeek-image.tar
  ZEEK_REPO: zeek/zeek
  ZEEK_REF: 1d2c12e9801018575f462a496b7da87e2cbd21e1
  CONFFLAGS: --generator=Ninja --build-type=Release

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.ZEEK_REPO }}
          ref: ${{ env.ZEEK_REF }}
          submodules: "recursive"

      - name: Determine git commit
        run: |
          echo "GITHUB_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Setup Docker image cache
        id: cache-docker-image
        uses: actions/cache@v3
        env:
          cache-name: cache-docker-image
        with:
          path: ${{ env.IMAGE_FILE }}
          key: ${{ env.GITHUB_SHA }}

      - uses: docker/setup-buildx-action@v2
        if: ${{ steps.cache-docker-image.outputs.cache-hit != 'true' }}

      - name: Build image
        if: ${{ steps.cache-docker-image.outputs.cache-hit != 'true' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          build-args: |
            CONFFLAGS=${{ env.CONFFLAGS }}
          load: true
          tags: zeektest:latest

      - name: Run btests
        if: ${{ steps.cache-docker-image.outputs.cache-hit != 'true' }}
        run: make -C docker/btest

      - name: Save image tarball
        if: ${{ steps.cache-docker-image.outputs.cache-hit != 'true' }}
        run: docker save -o ${{ env.IMAGE_FILE }} zeektest:latest
